"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv # type: ignore
import os
import dj_database_url # type: ignore

# Load environment variables from .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'insecure-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'army_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE CONFIG
ENV = os.getenv("ENV", "dev")  # set ENV=prod for production

if ENV == "prod" and os.getenv('DATABASE_URL'):
    # Use external database (e.g. Supabase)
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
else:
    # Use local Docker PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / "army_app" / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GRAPH_MODELS = {
  'all_applications': True,
  'group_models': True,
}

# Logging
LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version" : 1,
    "disable_existing_loggers" : False,
    "formatters" : {
        "verbose" : {
            "format" : "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
        },
        "simple" : {
            "format" : "%(levelname)s - %(message)s"
        },
        "color": {
            "()": "colorlog.ColoredFormatter",
            "format": "%(log_color)s%(levelname)s - %(message)s",
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "yellow",
                "ERROR": "red",
                "CRITICAL": "bold_red",
            },
        },
    },
    "handlers" : {
        "console" : {
            "class" : "logging.StreamHandler",
            "formatter" : "color",
        },
        # Rolling file for validate_data
        "load_data_file" : {
            "level" : "INFO",
            "class" : "logging.handlers.RotatingFileHandler",
            "filename" : os.path.join(LOG_DIR, "load_data.log"),
            "maxBytes" : 5 * 1024 * 1024, # 5 MB
            "backupCount" : 3, # keep 3 old logs
            "formatter" : "verbose",
        },
        # Rolling file for download_csv
        "download_csv_file" : {
            "level" : "INFO",
            "class" : "logging.handlers.RotatingFileHandler",
            "filename" : os.path.join(LOG_DIR, "download_csv.log"),
            "maxBytes" : 5 * 1024 * 1024, # 5 MB
            "backupCount" : 3, # keep 3 old logs
            "formatter" : "verbose",
        },
        # Rolling file for datasheet
        "datasheet_file" : {
            "level" : "INFO",
            "class" : "logging.handlers.RotatingFileHandler",
            "filename" : os.path.join(LOG_DIR, "datasheet.log"),
            "maxBytes" : 5 * 1024 * 1024, # 5 MB
            "backupCount" : 3, # keep 3 old logs
            "formatter" : "verbose",
        },
        "build_keywordcondition_file" : {
            "level" : "INFO",
            "class" : "logging.handlers.RotatingFileHandler",
            "filename" : os.path.join(LOG_DIR, "build_keywordcondition.log"),
            "maxBytes" : 5 * 1024 * 1024, # 5 MB
            "backupCount" : 3, # keep 3 old logs
            "formatter" : "verbose",
        },
    },
    "loggers" : {
        # Specific logger for data loader
        "load_data" : {
            "handlers" : ["console", "load_data_file"],
            "level" : "INFO",
            "propagate" : False,
        },
        # Specific logger for download csv
        "download_csv" : {
            "handlers" : ["console", "download_csv_file"],
            "level" : "INFO",
            "propagate" : False,
        },
        # Specific logger for datasheet
        "datasheet" : {
            "handlers" : ["console", "datasheet_file"],
            "level" : "WARNING",
            "propagate" : False,
        },
        # Specific logger for build_keywordcondition
        "build_keywordconditions" : {
            "handlers" : ["console", "build_keywordcondition_file"],
            "level" : "INFO",
            "propagate" : False,
        },
    },
}
