# Generated by Django 5.2.4 on 2025-08-05 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SPM', 'Space Marines'), ('TYR', 'Tyrannids'), ('ORK', 'Orks'), ('NEC', 'Necrons')], max_length=255)),
                ('rule_name', models.CharField(max_length=255)),
                ('faction_rule_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.faction')),
            ],
        ),
        migrations.AddField(
            model_name='detachment',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_key_words',
            field=models.ManyToManyField(blank=True, to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='key_words',
            field=models.ManyToManyField(blank=True, to='army_app.keyword'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction')),
                ('key_words', models.ManyToManyField(blank=True, to='army_app.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(null=True, upload_to='datasheets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('unit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasheet', to='army_app.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ArmyListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_count', models.PositiveIntegerField()),
                ('army_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='army_app.armylist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitPointBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_models', models.PositiveIntegerField(default=1)),
                ('max_models', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveIntegerField()),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_brackets', to='army_app.unit')),
            ],
            options={
                'ordering': ['min_models'],
            },
        ),
    ]
