# Generated by Django 5.2.4 on 2025-10-21 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SPM', 'Space Marines'), ('TYR', 'Tyrannids'), ('ORK', 'Orks'), ('NEC', 'Necrons')], max_length=255)),
                ('rule_name', models.CharField(max_length=255)),
                ('faction_rule_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArmyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.faction')),
            ],
        ),
        migrations.AddField(
            model_name='detachment',
            name='faction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.AddField(
            model_name='faction',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='army_app.keyword'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('faction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction')),
                ('keywords', models.ManyToManyField(blank=True, to='army_app.keyword')),
            ],
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('SPM', 'Space Marines'), ('TYR', 'Tyrannids'), ('ORK', 'Orks'), ('NEC', 'Necrons'), ('CUS', 'Adeptus Custodes'), ('MEC', 'Adeptus Mechanicus')], max_length=255),
        ),
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField()),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement', to='army_app.detachment')),
                ('keywords', models.ManyToManyField(blank=True, to='army_app.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='ArmyListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_count', models.PositiveIntegerField(default=1)),
                ('army_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='army_app.armylist')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.unit')),
                ('enhancement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army_app.enhancement')),
                ('is_warlord', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('enhancement__isnull', False)), fields=('army_list', 'enhancement'), name='unique_enhancement_per_army_list')],
            },
        ),
        migrations.RemoveField(
            model_name='faction',
            name='faction_rule_description',
        ),
        migrations.AddField(
            model_name='faction',
            name='rule_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='faction',
            name='rule_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.CreateModel(
            name='UnitPointBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_models', models.PositiveIntegerField(default=1)),
                ('max_models', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveIntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_brackets', to='army_app.unit')),
            ],
            options={
                'ordering': ['min_models'],
            },
        ),
        migrations.AlterField(
            model_name='detachment',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.PositiveIntegerField(default=1)),
                ('keywords', models.ManyToManyField(blank=True, to='army_app.keyword')),
                ('detachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leaders', to='army_app.armylistentry')),
                ('leader_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_assignments', to='army_app.armylistentry')),
            ],
            options={
                'unique_together': set(),
                'indexes': [models.Index(fields=['entry', 'leader_entry'], name='army_app_as_entry_i_c4ff29_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'leader_entry'), name='unique_leader_assignment')],
            },
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_to', to='army_app.unit')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='army_app.unit')),
                ('co_leaders', models.ManyToManyField(blank=True, help_text='Leaders that can co-lead the same unit.', to='army_app.unit')),
                ('keywords', models.ManyToManyField(blank=True, help_text='Leader must have ALL of these keywords (e.g., RELIC SHIELD).', related_name='leadership_required_for', to='army_app.keyword')),
            ],
            options={
                'unique_together': set(),
            },
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weapon_type', models.CharField(choices=[('RANGED', 'Ranged'), ('MELEE', 'Melee')], max_length=10)),
                ('weapon_range', models.CharField(blank=True, max_length=10, null=True)),
                ('attacks', models.CharField(max_length=10)),
                ('skill', models.CharField(max_length=10)),
                ('strength', models.CharField(max_length=10)),
                ('ap', models.CharField(max_length=10)),
                ('damage', models.CharField(max_length=10)),
                ('abilities', models.ManyToManyField(blank=True, to='army_app.ability')),
            ],
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datasheet', to='army_app.unit')),
                ('invulnerable_save', models.CharField(blank=True, max_length=10, null=True)),
                ('leadership', models.CharField(max_length=10)),
                ('movement', models.CharField(max_length=10)),
                ('objective_control', models.PositiveIntegerField()),
                ('armour_save', models.CharField(max_length=10)),
                ('toughness', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wargear_options', models.TextField(blank=True, default='')),
                ('wounds', models.PositiveIntegerField()),
                ('abilities', models.ManyToManyField(blank=True, related_name='datasheet_abilities', to='army_app.ability')),
                ('wargear_abilities', models.ManyToManyField(blank=True, related_name='datasheet_wargear', to='army_app.ability')),
                ('melee_weapons', models.ManyToManyField(blank=True, related_name='datasheets_melee', to='army_app.weapon')),
                ('ranged_weapons', models.ManyToManyField(blank=True, related_name='datasheets_ranged', to='army_app.weapon')),
            ],
        ),
    ]
