# Generated by Django 5.2.4 on 2025-08-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armylist',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='faction',
            name='faction_rule_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('SPM', 'Space Marines'), ('TYR', 'Tyrannids'), ('ORK', 'Orks'), ('NEC', 'Necrons'), ('CUS', 'Adeptus Custodes')], max_length=255),
        ),
        migrations.CreateModel(
            name='Enhancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('points', models.PositiveIntegerField()),
                ('detachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhancement', to='army_app.detachment')),
                ('key_words', models.ManyToManyField(blank=True, related_name='required_keywords', to='army_app.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='armylistentry',
            name='enhancement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army_app.enhancement'),
        ),
    ]
