# Generated by Django 5.2.7 on 2025-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_inital'),
    ]

    operations = [
        migrations.AddField(
            model_name='armylist',
            name='battle_size',
            field=models.CharField(choices=[('incursion', 'Incursion (0–1000 pts)'), ('strike', 'Strike Force (1000–2000 pts)'), ('onslaught', 'Onslaught (2000–3000 pts)')], default='incursion', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armylist',
            name='point_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
