# Generated by Django 5.2.6 on 2025-10-24 10:57

from django.db import migrations
import csv
import logging
import os
from pathlib import Path

# Import loaders
from army_app.data import (
    load_factions, load_detachments, load_enhancements, load_stratagems,
    load_abilities, load_weapons, load_units, load_unit_point_brackets,
    load_data_sheet, load_leadership
)

BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = os.path.join(BASE_DIR, "logs")
logger = logging.getLogger("data_migration")

def obj_to_dict(obj):
    return {
        field.name: getattr(obj, field.name)
        for field in obj._meta.fields
        if field.name not in ["id"]
    }

def update_csv_edit_flag(csv_path, objs):
    # Skip directories (e.g. datasheets)
    if not csv_path.is_file():
        return

    with open(csv_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
        fieldnames = rows[0].keys() if rows else []

    updated = False
    for row in rows:
        obj_id = str(row.get("id", "")).strip()
        if any(str(o.id) == obj_id and getattr(o, "is_edit", False) for o in objs):
            row["edit"] = "0"
            updated = True

    if updated:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)
        logger.info(f"[Migration] Updated edit flags in {csv_path.name}")

def load_initial_data(apps, schema_editor):
    base_dir = BASE_DIR / "data"

    loaders = [
        ("Factions", base_dir / "factions.csv", load_factions),
        ("Detachments", base_dir / "detachments.csv", load_detachments),
        ("Enhancements", base_dir / "enhancements.csv", load_enhancements),
        ("Stratagems", base_dir / "stratagems.csv", load_stratagems),
        ("Abilities", base_dir / "abilities.csv", load_abilities),
        ("Weapons", base_dir / "weapons.csv", load_weapons),
        ("Units", base_dir / "units.csv", load_units),
        ("Unit Point Brackets", base_dir / "unit_point_brackets.csv", load_unit_point_brackets),
        ("Datasheets", base_dir / "datasheets", load_data_sheet),
        ("Leadership", base_dir / "leadership.csv", load_leadership),
    ]

    for name, path, loader in loaders:
        errors, objs = loader(path)
        if errors:
            logger.error(f"[Migration] Skipped {name}: {len(errors)} errors")
            continue

        for obj in objs:
            Model = apps.get_model(obj._meta.app_label, obj._meta.model_name)

            m2m_fields = {
                f.name: getattr(obj, f.name)
                for f in obj._meta.many_to_many
                if getattr(obj, f.name, None)
            }

            defaults = obj_to_dict(obj)

            # Grab edit flag from object
            is_edit = getattr(obj, "is_edit", False)
            # Create or update main object
            instance, created = Model.objects.update_or_create(id=obj.id, defaults={**defaults})

            if not created and not is_edit:
                # Skip if already exists and not edit
                continue
            
            # Save object
            instance.save()

            # Set M2M relations (if any)
            for field_name, related_objs in m2m_fields.items():
                getattr(instance, field_name).set(related_objs)

        logger.info(f"[Migration] Loaded {len(objs)} {name}")
        update_csv_edit_flag(path, objs)


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_inital'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_code=migrations.RunPython.noop),
    ]
