# Generated by Django 5.2.6 on 2025-10-24 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_inital'),
    ]

    operations = [
    ]
