# Generated by Django 5.2.4 on 2025-08-04 02:42

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='data_sheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.datasheet'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='num_models',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
