# Generated by Django 5.2.4 on 2025-08-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0002_alter_armylist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armylistentry',
            name='model_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='key_words',
            field=models.ManyToManyField(blank=True, to='army_app.keyword'),
        ),
        migrations.AddConstraint(
            model_name='armylistentry',
            constraint=models.UniqueConstraint(condition=models.Q(('enhancement__isnull', False)), fields=('army_list', 'enhancement'), name='unique_enhancement_per_army_list'),
        ),
    ]
