# Generated by Django 5.2.4 on 2025-08-04 23:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0002_faction_rule_unit_detachment_alter_datasheet_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detachment',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='rule',
        ),
        migrations.AddField(
            model_name='detachment',
            name='detachment_rule_description',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='detachment',
            name='detachment_rule_key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_rule_description',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faction',
            name='faction_rule_key_words',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
