# Generated by Django 5.2.4 on 2025-08-04 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0003_remove_detachment_rule_remove_faction_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detachment',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
    ]
