# Generated by Django 5.2.7 on 2025-11-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0003_alter_armylist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armylist',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment'),
        ),
    ]
