# Generated by Django 5.2.4 on 2025-08-09 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0003_alter_armylistentry_model_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='armylistentry',
            name='is_warlord',
            field=models.BooleanField(default=False),
        ),
    ]
