# Generated by Django 5.2.4 on 2025-08-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0004_detachment_faction'),
    ]

    operations = [
        migrations.AddField(
            model_name='faction',
            name='faction_rule_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
