# Generated by Django 5.2.7 on 2025-11-22 14:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0004_alter_armylist_detachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadership',
            old_name='attached_unit',
            new_name='attachable_unit',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='description',
        ),
        migrations.RemoveField(
            model_name='detachment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='detachment',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='enhancement',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='rule_description',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='rule_name',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='keywords',
        ),
        migrations.AddField(
            model_name='ability',
            name='ability_type',
            field=models.CharField(choices=[('FACTION_RULE', 'Faction Rule'), ('DETACHMENT_RULE', 'Detachment Rule'), ('UNIT_ABILITY', 'Unit Ability'), ('WEAPON_ABILITY', 'Weapon Ability'), ('WARGEAR_ABILITY', 'Wargear Ability'), ('CORE_RULE', 'Core Rule')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detachment',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ability_type': 'DETACHMENT_RULE'}, related_name='detachments', to='army_app.ability'),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='and_keywords',
            field=models.ManyToManyField(blank=True, related_name='enhancements_requiring', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='not_keywords',
            field=models.ManyToManyField(blank=True, related_name='enhancements_forbidding', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='faction',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ability_type': 'FACTION_RULE'}, related_name='factions', to='army_app.ability'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='and_keywords',
            field=models.ManyToManyField(blank=True, related_name='stratagems_requiring', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='not_keywords',
            field=models.ManyToManyField(blank=True, related_name='stratagems_forbidding', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='unit',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ability_type': 'UNIT_ABILITY'}, related_name='unit_abilities', to='army_app.ability'),
        ),
        migrations.AddField(
            model_name='unit',
            name='armour_save',
            field=models.CharField(default='3+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='invulnerable_save',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='ld',
            field=models.CharField(default='6+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='melee_weapons',
            field=models.ManyToManyField(blank=True, related_name='datasheets_melee', to='army_app.weapon'),
        ),
        migrations.AddField(
            model_name='unit',
            name='movement',
            field=models.CharField(default='6', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='objective_control',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='ranged_weapons',
            field=models.ManyToManyField(blank=True, related_name='datasheets_ranged', to='army_app.weapon'),
        ),
        migrations.AddField(
            model_name='unit',
            name='toughness',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='wargear_abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ability_type': 'WARGEAR_ABILITY'}, related_name='wargear_abilities', to='army_app.ability'),
        ),
        migrations.AddField(
            model_name='unit',
            name='wargear_options',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='unit',
            name='wounds',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stratagem',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stratagems', to='army_app.detachment'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ability_type': 'WEAPON_ABILITY'}, to='army_app.ability'),
        ),
        migrations.CreateModel(
            name='AbilityEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_description', models.TextField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='army_app.ability')),
                ('and_keywords', models.ManyToManyField(blank=True, related_name='and_effects', to='army_app.keyword')),
                ('not_keywords', models.ManyToManyField(blank=True, related_name='not_effects', to='army_app.keyword')),
                ('or_keywords', models.ManyToManyField(blank=True, related_name='or_effects', to='army_app.keyword')),
            ],
        ),
        migrations.DeleteModel(
            name='DataSheet',
        ),
    ]
