# Generated by Django 5.2.4 on 2025-08-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0004_armylistentry_is_warlord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('cost', models.PositiveIntegerField(default=1)),
                ('is_core', models.BooleanField(default=False)),
                ('detachments', models.ManyToManyField(blank=True, to='army_app.detachment')),
                ('key_words', models.ManyToManyField(blank=True, to='army_app.keyword')),
            ],
        ),
        migrations.AddField(
            model_name='armylistentry',
            name='stratagems',
            field=models.ManyToManyField(blank=True, to='army_app.stratagem'),
        ),
    ]
