# Generated by Django 5.2.7 on 2026-04-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0005_rename_attached_unit_leadership_attachable_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COMMAND', 'Command phase'), ('MOVEMENT', 'Movement phase'), ('SHOOTING', 'Shooting phase'), ('CHARGE', 'Charge phase'), ('Fight', 'Fight phase')], max_length=255)),
                ('turn', models.CharField(choices=[('YOURS', 'Your turn'), ('OPP', "Your opponent's turn")], max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='stratagem',
            old_name='description',
            new_name='effect',
        ),
        migrations.RemoveField(
            model_name='abilityeffect',
            name='and_keywords',
        ),
        migrations.RemoveField(
            model_name='abilityeffect',
            name='not_keywords',
        ),
        migrations.RemoveField(
            model_name='abilityeffect',
            name='or_keywords',
        ),
        migrations.RemoveField(
            model_name='enhancement',
            name='and_keywords',
        ),
        migrations.RemoveField(
            model_name='enhancement',
            name='not_keywords',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='and_keywords',
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='not_keywords',
        ),
        migrations.AddField(
            model_name='abilityeffect',
            name='keyword_expression',
            field=models.TextField(default='', help_text='e.g. ADEPTUS ASTARTES AND (VEHICLE OR MOUNTED)'),
        ),
        migrations.AddField(
            model_name='abilityeffect',
            name='keywords',
            field=models.ManyToManyField(related_name='ability_effect_keywords', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='keyword_expression',
            field=models.TextField(default='', help_text='e.g. ADEPTUS ASTARTES AND (VEHICLE OR MOUNTED)'),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='keywords',
            field=models.ManyToManyField(related_name='enhancement_keywords', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='keyword_expression',
            field=models.TextField(default='', help_text='e.g. ADEPTUS ASTARTES AND (VEHICLE OR MOUNTED)'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='keywords',
            field=models.ManyToManyField(related_name='stratagem_keywords', to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='restrictions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='target',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='faction',
            name='abilities',
            field=models.ManyToManyField(blank=True, limit_choices_to={'ability_type': 'FACTION_RULE'}, related_name='granted_to_factions', to='army_app.ability'),
        ),
        migrations.CreateModel(
            name='KeyWordCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(blank=True, choices=[('AND', 'AND'), ('OR', 'OR'), ('NOT', 'NOT')], help_text='Logical operator, null means leaf node', max_length=255, null=True)),
                ('keyword', models.ForeignKey(blank=True, help_text='Set only for leaf nodes', null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.keyword')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='army_app.keywordcondition')),
            ],
        ),
        migrations.AddField(
            model_name='abilityeffect',
            name='auto_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army_app.keywordcondition'),
        ),
        migrations.AddField(
            model_name='enhancement',
            name='auto_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army_app.keywordcondition'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='auto_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='army_app.keywordcondition'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='when',
            field=models.ManyToManyField(blank=True, related_name='stratagem_phase', to='army_app.phase'),
        ),
    ]
