# Generated by Django 5.2.4 on 2025-08-05 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0005_faction_faction_rule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='detachment',
        ),
        migrations.CreateModel(
            name='Army_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('point_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('detachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment')),
                ('faction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.faction')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.unit')),
            ],
        ),
    ]
