# Generated by Django 5.2.4 on 2025-08-09 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0005_stratagem_armylistentry_stratagems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detachment',
            old_name='key_words',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='enhancement',
            old_name='key_words',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='faction',
            old_name='faction_key_words',
            new_name='faction_keywords',
        ),
        migrations.RenameField(
            model_name='stratagem',
            old_name='key_words',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='key_words',
            new_name='keywords',
        ),
    ]
