# Generated by Django 5.2.4 on 2025-08-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0006_remove_unit_detachment_army_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Army_List',
        ),
    ]
