# Generated by Django 5.2.4 on 2025-08-09 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0006_rename_key_words_detachment_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stratagem',
            old_name='detachments',
            new_name='detachment',
        ),
    ]
