# Generated by Django 5.2.7 on 2026-04-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0006_phase_rename_description_stratagem_effect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityeffect',
            name='keyword_expression',
            field=models.TextField(blank=True, default='', help_text='e.g. ADEPTUS ASTARTES AND (VEHICLE OR MOUNTED)'),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='keyword_expression',
            field=models.TextField(blank=True, default='', help_text='e.g. ADEPTUS ASTARTES AND (VEHICLE OR MOUNTED)'),
        ),
        migrations.AlterField(
            model_name='stratagem',
            name='keyword_expression',
            field=models.TextField(blank=True, default='', help_text='e.g. ADEPTUS ASTARTES AND (VEHICLE OR MOUNTED)'),
        ),
    ]
