# Generated by Django 5.2.4 on 2025-08-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0007_rename_detachments_stratagem_detachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stratagem',
            name='is_core',
        ),
    ]
