# Generated by Django 5.2.7 on 2026-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0007_alter_abilityeffect_keyword_expression_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stratagem',
            name='when',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='when',
            field=models.TextField(blank=True, default=''),
        ),
    ]
