# Generated by Django 5.2.7 on 2026-08-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0008_remove_stratagem_when_stratagem_when'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='abilityeffect',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_effect_phase', to='army_app.phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(choices=[('PRE-BATTLE', 'Pre-battle phase'), ('COMMAND', 'Command phase'), ('MOVEMENT', 'Movement phase'), ('SHOOTING', 'Shooting phase'), ('CHARGE', 'Charge phase'), ('FIGHT', 'Fight phase'), ('ANY', 'Any phase')], max_length=255),
        ),
        migrations.AlterField(
            model_name='phase',
            name='turn',
            field=models.CharField(choices=[('YOUR', 'Your turn'), ('OPP', "Your opponent's turn")], max_length=255),
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='when',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='when',
            field=models.ManyToManyField(blank=True, related_name='stratagem_phase', to='army_app.phase'),
        ),
    ]
