# Generated by Django 5.2.4 on 2025-08-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0008_remove_stratagem_is_core'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stratagem',
            name='keywords',
            field=models.ManyToManyField(to='army_app.keyword'),
        ),
    ]
