# Generated by Django 5.2.4 on 2025-08-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0009_alter_stratagem_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armylistentry',
            name='stratagems',
        ),
    ]
