# Generated by Django 5.2.7 on 2026-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0009_scrapedpage_abilityeffect_phase_alter_phase_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abilityeffect',
            name='phase',
        ),
        migrations.AddField(
            model_name='abilityeffect',
            name='phase',
            field=models.ManyToManyField(blank=True, related_name='ability_effect_phase', to='army_app.phase'),
        ),
    ]
