# Generated by Django 5.2.4 on 2025-08-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0010_remove_armylistentry_stratagems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faction',
            old_name='faction_keywords',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='faction_rule_description',
        ),
        migrations.AddField(
            model_name='faction',
            name='rule_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datasheet', to='army_app.unit'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='rule_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.AlterField(
            model_name='unitpointbracket',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_brackets', to='army_app.unit'),
        ),
    ]
