# Generated by Django 5.2.7 on 2026-08-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0010_remove_abilityeffect_phase_abilityeffect_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='turn',
            field=models.CharField(choices=[('YOUR', 'Your turn'), ('OPP', "Your opponent's turn"), ('ANY', 'Any turn')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='when',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='when',
            field=models.TextField(blank=True, default=''),
        ),
    ]
