# Generated by Django 5.2.4 on 2025-08-11 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0011_rename_faction_keywords_faction_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='upload_file',
            field=models.FileField(blank=True, upload_to='datasheets/'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='army_app.faction'),
        ),
        migrations.AlterField(
            model_name='faction',
            name='rule_name',
            field=models.CharField(max_length=255),
        ),
    ]
