# Generated by Django 5.2.7 on 2026-08-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0011_alter_phase_turn_remove_stratagem_when_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('SPM', 'Space Marines'), ('TYR', 'Tyrannids'), ('ORK', 'Orks'), ('NEC', 'Necrons'), ('CUS', 'Adeptus Custodes'), ('MEC', 'Adeptus Mechanicus'), ('AEL', 'Aeldari'), ('DRU', 'Drukhari')], max_length=255),
        ),
    ]
