# Generated by Django 5.2.7 on 2026-08-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0012_alter_faction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('SOR', 'Adepta Sororitas'), ('CUS', 'Adeptus Custodes'), ('MEC', 'Adeptus Mechanicus'), ('MIL', 'Astra Militarum'), ('GRY', 'Grey Knights'), ('IAG', 'Imperial Agents'), ('IKN', 'Imperial Knights'), ('SPM', 'Space Marines'), ('CDM', 'Chaos Daemons'), ('CKN', 'Chaos Knights'), ('CSM', 'Chaos Space Marines'), ('DGD', 'Death Guard'), ('EMC', "Emperor's Children"), ('THS', 'Thousand Sons'), ('WET', 'World Eaters'), ('AEL', 'Aeldari'), ('DRU', 'Drukhari'), ('GEN', 'Genestealer Cults'), ('VOT', 'Leagues of Votann'), ('NEC', 'Necrons'), ('ORK', 'Orks'), ('TAU', "T'au Empire"), ('TYR', 'Tyrannids')], max_length=255),
        ),
    ]
