# Generated by Django 5.2.4 on 2025-08-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0012_alter_datasheet_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armylist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='faction',
            name='rule_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='stratagem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='detachment',
        ),
        migrations.AlterField(
            model_name='stratagem',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='army_app.keyword'),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='army_app.detachment'),
        ),
    ]
