# Generated by Django 5.2.7 on 2026-09-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0013_alter_faction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='turn',
        ),
        migrations.AddField(
            model_name='abilityeffect',
            name='turn_scope',
            field=models.CharField(choices=[('YOUR', 'Your turn'), ('OPP', "Opponent's turn"), ('ANY', 'Either turn')], default='ANY', max_length=255),
        ),
        migrations.AddField(
            model_name='stratagem',
            name='turn_scope',
            field=models.CharField(choices=[('YOUR', 'Your turn'), ('OPP', "Opponent's turn"), ('ANY', 'Either turn')], default='ANY', max_length=255),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(choices=[('PRE-BATTLE', 'Pre-battle phase'), ('COMMAND', 'Command phase'), ('MOVEMENT', 'Movement phase'), ('SHOOTING', 'Shooting phase'), ('CHARGE', 'Charge phase'), ('FIGHT', 'Fight phase'), ('END BATTLE TURN', 'End of the battle turn'), ('BEGINNING BATTLE TURN', 'Beginning of the battle turn'), ('ANY', 'Any phase')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='when',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='when',
            field=models.ManyToManyField(blank=True, default='ANY', related_name='stratagem_phase', to='army_app.phase'),
        ),
    ]
