# Generated by Django 5.2.4 on 2025-08-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0013_alter_armylist_name_alter_detachment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='enhancement',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
