# Generated by Django 5.2.6 on 2025-09-13 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0014_alter_datasheet_source_alter_enhancement_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='leader_shares',
            field=models.ManyToManyField(blank=True, help_text='Leaders that may be selected together for the same attached unit.', to='army_app.unit'),
        ),
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_to', to='army_app.unit')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='army_app.unit')),
            ],
            options={
                'unique_together': {('leader', 'attached_unit')},
            },
        ),
    ]
