# Generated by Django 5.2.7 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0014_remove_phase_turn_abilityeffect_turn_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityeffect',
            name='turn_scope',
            field=models.CharField(choices=[('YOUR', 'Your turn'), ('OPP', "Opponent's turn"), ('END BATTLE TURN', 'End of the battle turn'), ('BEGINNING BATTLE TURN', 'Beginning of the battle turn'), ('ANY', 'Either turn')], default='ANY', max_length=255),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(choices=[('PRE-BATTLE', 'Pre-battle phase'), ('COMMAND', 'Command phase'), ('MOVEMENT', 'Movement phase'), ('SHOOTING', 'Shooting phase'), ('CHARGE', 'Charge phase'), ('FIGHT', 'Fight phase'), ('ANY', 'Any phase')], max_length=255),
        ),
        migrations.AlterField(
            model_name='stratagem',
            name='turn_scope',
            field=models.CharField(choices=[('YOUR', 'Your turn'), ('OPP', "Opponent's turn"), ('END BATTLE TURN', 'End of the battle turn'), ('BEGINNING BATTLE TURN', 'Beginning of the battle turn'), ('ANY', 'Either turn')], default='ANY', max_length=255),
        ),
    ]
