# Generated by Django 5.2.7 on 2026-10-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0015_alter_abilityeffect_turn_scope_alter_phase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratagem',
            name='phase',
            field=models.ManyToManyField(blank=True, default='ANY', related_name='stratagem_phase', to='army_app.phase'),
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='when',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='when',
            field=models.TextField(blank=True, default=''),
        ),
    ]
