# Generated by Django 5.2.6 on 2025-09-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0015_unit_leader_shares_leadership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='leader_shares',
        ),
        migrations.AddField(
            model_name='leadership',
            name='co_leaders',
            field=models.ManyToManyField(blank=True, help_text='Leaders that can co-lead the same unit.', to='army_app.leadership'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='required_keywords',
            field=models.ManyToManyField(blank=True, help_text='Leader must have ALL of these keywords (e.g., RELIC SHIELD).', related_name='leadership_required_for', to='army_app.keyword'),
        ),
        migrations.CreateModel(
            name='AssignedLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leaders', to='army_app.armylistentry')),
                ('leader_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_assignments', to='army_app.armylistentry')),
            ],
            options={
                'unique_together': {('leader_entry', 'entry')},
            },
        ),
    ]
