# Generated by Django 5.2.7 on 2026-10-06 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0016_stratagem_phase_remove_stratagem_when_stratagem_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedpage',
            name='page_type',
            field=models.CharField(choices=[('faction cluster', 'Faction Cluster'), ('unit cluster', 'Unit Cluster'), ('unknown cluster', 'Unknown Cluster')], default='unit cluster', max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
        migrations.RemoveField(
            model_name='stratagem',
            name='detachment',
        ),
        migrations.AddField(
            model_name='stratagem',
            name='detachment',
            field=models.ManyToManyField(blank=True, related_name='stratagems', to='army_app.detachment'),
        ),
        migrations.CreateModel(
            name='ScrapedPageLoadResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('Faction', 'Faction'), ('Detachment', 'Detachment'), ('Stratagem', 'Stratagem'), ('Enhancement', 'Enhancement'), ('Unit', 'Unit'), ('UnitPointBracket', 'Unit Point Bracket'), ('Leadership', 'Leadership'), ('Ability', 'Ability'), ('AbilityEffect', 'Ability Effect'), ('Phase', 'Phase'), ('KeyWord', 'Keyword')], max_length=255)),
                ('source_key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('unloaded', 'Unloaded'), ('loaded', 'Loaded'), ('load_failed', 'Load Failed')], default='unloaded', max_length=255)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('loaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(help_text='The result of processing a scraped page', on_delete=django.db.models.deletion.CASCADE, related_name='load_results', to='army_app.scrapedpage')),
            ],
            options={
                'ordering': ['page', 'target_model', 'source_key'],
                'indexes': [models.Index(fields=['target_model', 'status'], name='army_app_sc_target__d47a14_idx')],
                'constraints': [models.UniqueConstraint(fields=('page', 'target_model', 'source_key'), name='unique_load_result_per_item')],
            },
        ),
    ]
