# Generated by Django 5.2.6 on 2025-09-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0016_remove_unit_leader_shares_leadership_co_leaders_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedleader',
            unique_together={('entry', 'leader_entry')},
        ),
    ]
