# Generated by Django 5.2.7 on 2026-10-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0017_scrapedpage_page_type_alter_scrapedpage_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stratagem',
            old_name='detachment',
            new_name='detachments',
        ),
    ]
