# Generated by Django 5.2.6 on 2025-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0017_alter_assignedleader_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignedleader',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='assignedleader',
            index=models.Index(fields=['entry', 'leader_entry'], name='army_app_as_entry_i_c4ff29_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignedleader',
            constraint=models.UniqueConstraint(fields=('entry', 'leader_entry'), name='unique_leader_assignment'),
        ),
    ]
