# Generated by Django 5.2.6 on 2025-09-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0018_alter_assignedleader_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadership',
            unique_together=set(),
        ),
    ]
