# Generated by Django 5.2.7 on 2026-10-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0018_rename_detachment_stratagem_detachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='scrapedpage',
            name='page_type',
            field=models.CharField(choices=[('faction cluster', 'Faction Cluster'), ('unit cluster', 'Unit Cluster'), ('unknown cluster', 'Unknown Cluster')], default='unknown cluster', max_length=255),
        ),
    ]
