# Generated by Django 5.2.4 on 2025-09-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0019_alter_leadership_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leadership',
            old_name='required_keywords',
            new_name='keywords',
        ),
        migrations.AlterField(
            model_name='leadership',
            name='co_leaders',
            field=models.ManyToManyField(blank=True, help_text='Leaders that can co-lead the same unit.', to='army_app.unit'),
        ),
    ]
