# Generated by Django 5.2.4 on 2025-09-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0020_rename_required_keywords_leadership_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='datasheet',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='datasheet',
            name='source',
        ),
        migrations.RemoveField(
            model_name='datasheet',
            name='upload_file',
        ),
        migrations.AddField(
            model_name='datasheet',
            name='invulnerable_save',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='leadership',
            field=models.CharField(default='6+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='movement',
            field=models.CharField(default='6', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='objective_control',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='save',
            field=models.CharField(default='3+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='toughness',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='wargear_options',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='wounds',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasheet',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='datasheet_abilities', to='army_app.ability'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='wargear_abilities',
            field=models.ManyToManyField(blank=True, related_name='datasheet_wargear', to='army_app.ability'),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weapon_type', models.CharField(choices=[('RANGED', 'Ranged'), ('MELEE', 'Meleee')], max_length=10)),
                ('weapon_range', models.CharField(blank=True, max_length=10, null=True)),
                ('attacks', models.CharField(max_length=10)),
                ('skill', models.CharField(max_length=10)),
                ('strength', models.CharField(max_length=10)),
                ('ap', models.CharField(max_length=10)),
                ('damage', models.CharField(max_length=10)),
                ('abilities', models.ManyToManyField(blank=True, to='army_app.ability')),
            ],
        ),
        migrations.AddField(
            model_name='datasheet',
            name='melee_weapons',
            field=models.ManyToManyField(blank=True, related_name='datasheets_melee', to='army_app.weapon'),
        ),
        migrations.AddField(
            model_name='datasheet',
            name='ranged_weapons',
            field=models.ManyToManyField(blank=True, related_name='datasheets_ranged', to='army_app.weapon'),
        ),
    ]
