# Generated by Django 5.2.6 on 2025-09-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0021_ability_rename_uploaded_at_datasheet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterField(
            model_name='weapon',
            name='weapon_type',
            field=models.CharField(choices=[('RANGED', 'Ranged'), ('MELEE', 'Melee')], max_length=10),
        ),
    ]
