# Generated by Django 5.2.6 on 2025-09-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0022_alter_ability_options_alter_weapon_weapon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheet',
            old_name='save',
            new_name='armour_save',
        ),
    ]
