# Generated by Django 5.2.4 on 2025-10-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0001_squashed_0023_rename_save_datasheet_armour_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='armour_save',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='leadership',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='movement',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='objective_control',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='toughness',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='wounds',
            field=models.PositiveIntegerField(),
        ),
    ]
