# Generated by Django 5.2.4 on 2025-10-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('army_app', '0024_alter_datasheet_armour_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('SPM', 'Space Marines'), ('TYR', 'Tyrannids'), ('ORK', 'Orks'), ('NEC', 'Necrons'), ('CUS', 'Adeptus Custodes'), ('MEC', 'Adeptus Mechanicus')], max_length=255),
        ),
    ]
